// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: gettodo/gettodo.proto

package gettodo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RandomToDo_GetToDo_FullMethodName = "/RandomToDo/GetToDo"
)

// RandomToDoClient is the client API for RandomToDo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RandomToDoClient interface {
	GetToDo(ctx context.Context, in *GetToDoRequest, opts ...grpc.CallOption) (*GetToDoResponse, error)
}

type randomToDoClient struct {
	cc grpc.ClientConnInterface
}

func NewRandomToDoClient(cc grpc.ClientConnInterface) RandomToDoClient {
	return &randomToDoClient{cc}
}

func (c *randomToDoClient) GetToDo(ctx context.Context, in *GetToDoRequest, opts ...grpc.CallOption) (*GetToDoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToDoResponse)
	err := c.cc.Invoke(ctx, RandomToDo_GetToDo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RandomToDoServer is the server API for RandomToDo service.
// All implementations must embed UnimplementedRandomToDoServer
// for forward compatibility.
type RandomToDoServer interface {
	GetToDo(context.Context, *GetToDoRequest) (*GetToDoResponse, error)
	mustEmbedUnimplementedRandomToDoServer()
}

// UnimplementedRandomToDoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRandomToDoServer struct{}

func (UnimplementedRandomToDoServer) GetToDo(context.Context, *GetToDoRequest) (*GetToDoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToDo not implemented")
}
func (UnimplementedRandomToDoServer) mustEmbedUnimplementedRandomToDoServer() {}
func (UnimplementedRandomToDoServer) testEmbeddedByValue()                    {}

// UnsafeRandomToDoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RandomToDoServer will
// result in compilation errors.
type UnsafeRandomToDoServer interface {
	mustEmbedUnimplementedRandomToDoServer()
}

func RegisterRandomToDoServer(s grpc.ServiceRegistrar, srv RandomToDoServer) {
	// If the following call pancis, it indicates UnimplementedRandomToDoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RandomToDo_ServiceDesc, srv)
}

func _RandomToDo_GetToDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToDoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RandomToDoServer).GetToDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RandomToDo_GetToDo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RandomToDoServer).GetToDo(ctx, req.(*GetToDoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RandomToDo_ServiceDesc is the grpc.ServiceDesc for RandomToDo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RandomToDo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RandomToDo",
	HandlerType: (*RandomToDoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToDo",
			Handler:    _RandomToDo_GetToDo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gettodo/gettodo.proto",
}
